### ISSUE TITLE
Discord invite link is broken

### ISSUE THREAD

**Issue by Samathingamajig** [nguyenphuminh/FreakC#2]
The Discord invite link in [README.md](https://github.com/nguyenphuminh/FreakC/blob/master/README.md#what-is-freakc-) has stopped working.

If you do make a new link, make sure to set it to never expire and not have a limit on the number of users.

![image](https://user-images.githubusercontent.com/29130894/109366081-23528d80-7858-11eb-896e-9780e6f8b530.png)

**Comment by nguyenphuminh** [comment]
Thanks a lot for the issue! The invitation link is updated now.
